import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignOutButton, UserButton } from "@clerk/nextjs";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <SignedOut>
            <SignInButton/>
            <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base px-6 py-3">
              Sign In  </button>
            <SignOutButton/>
          </SignedOut>
          
            <SignedIn>
              <UserButton/>
              {children}
            </SignedIn>
          
        
      </body>
    </html>
    </ClerkProvider>
  );
}
